import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ModulesService {
  menu: any[] = [
    {
      name: 'Inventeario',
      id: 1,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Almacen',
      id: 2,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Requisiciones',
      id: 3,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Ordenes de compra',
      id: 4,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Empleados',
      id: 5,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Clientes',
      id: 6,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Proveedores',
      id: 7,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Productos',
      id: 8,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Tipo de cambio',
      id: 9,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Usuarios',
      id: 10,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Inventeario',
      id: 11,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Almacen',
      id: 12,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Requisiciones',
      id: 13,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Ordenes de compra',
      id: 14,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Empleados',
      id: 15,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Clientes',
      id: 16,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Proveedores',
      id: 17,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Productos',
      id: 18,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Tipo de cambio',
      id: 19,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Usuarios',
      id: 20,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Inventeario',
      id: 21,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Almacen',
      id: 22,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Requisiciones',
      id: 23,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Ordenes de compra',
      id: 24,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Empleados',
      id: 25,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Clientes',
      id: 26,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Proveedores',
      id: 27,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Productos',
      id: 28,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Tipo de cambio',
      id: 29,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Usuarios',
      id: 30,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'INICIO',
      id: 31,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'Dashboard',
      id: 32,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'CATÁLOGOS',
      id: 33,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'MÓDULOS',
      id: 34,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'FINANZAS',
      id: 35,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
    {
      name: 'CONFIGURACIÓN',
      id: 36,
      show: false,
      read: false,
      edit: false,
      delete: false,
      create: false,
    },
  ];
  constructor() {}
}



